services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30" # Check 30s Intervals
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Needs this to check for changes
  postgres:
    image: postgres:16.8
    container_name: pga-postgresql
    secrets:
      - db-password
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: project_a
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "project_a" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pga_pg_data:/var/lib/postgresql/data
  backend:
    image: eye1985/project-a:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - '8080:8080'
    depends_on:
      - postgres
volumes:
  pga_pg_data:
secrets:
  db-password:
    file: ./secret/password.txt